# Common things to do in a macOS tool CI pipeline
name: macOS Tools

on:
  workflow_call:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          ./build_and_copy.sh .
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: |
          xcodebuild test -scheme swift-conventional-commit-parser -destination "OS=13.0"

