# Common things to do in a macOS tool CI pipeline
name: macOS Tools

on:
  workflow_call:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          ./build_and_copy.sh .
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: |
          git clone https://github.com/DavidBrunow/CI-Tooling.git CI-Tooling --depth 1
          ./CI-Tooling/unpack.sh
          defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
          xcodebuild test -scheme swift-conventional-commit-parser -destination "OS=13.0"
          defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool NO

